#!/bin/bash

for file in /home/$USER/model6/slurm-out/*/model6/model6.bestlhoods
do
sed '1d' "$file" > "$file.trimmed"

cat /home/$USER/model6/slurm-out/*/model6/model6.bestlhoods.trimmed > model6.bestlhoods

done
