#!/bin/bash

for d in */
do

for file in /projects/f_mlp195/hoey/bootSFS_279fish_1068loci_model6/*/slurm-out/*/Ne279_1068loci/Ne279_1068loci.bestlhoods
do
sed '1d' "$file" > "$file.trimmed"

cat /projects/f_mlp195/hoey/bootSFS_279fish_1068loci_model6/$d/slurm-out/*/Ne279_1068loci/Ne279_1068loci.bestlhoods.trimmed > /projects/f_mlp195/hoey/bootSFS_279fish_1068loci_model6/$d/cis_sfs_summary
done

done
