#!/bin/bash

for file in /home/$USER/Ne278_1070loci/model6/slurm-out/*/model6/model6.bestlhoods
do
sed '1d' "$file" > "$file.trimmed"

cat /home/$USER/Ne278_1070loci/model6/slurm-out/*/model6/model6.bestlhoods.trimmed > /home/$USER/Ne278_1070loci/model6/model6.bestlhoods

done
